const NOT_FOUND_ERROR_CODE = 404;
const BAD_DATA_CODE = 400;
const SERVER_ERROR_CODE = 500;
const CONFLICT_ERROR = 409;

module.exports = {
  NOT_FOUND_ERROR_CODE, BAD_DATA_CODE, SERVER_ERROR_CODE, CONFLICT_ERROR,
};
